In [ ]:
#text representation or feature engineering
#text into numbers

**LABEL ENCODING**

**ONE HOT ENCODING**

In [ ]:
#similar words dont have similar representation
#consumes too much memory
#out of vocubulary problem
#no fixed length represtaion

**BAG OF WORDS**

In [ ]:
#count vectorizier
#LIMITATION
#comsumes a lot of memory (sparse representation)

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df= pd.read_csv(r'/content/spam.csv')
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [ ]:
'''def get_spam_number(x):
  if x=='spam':
    return 1
  return 0'''
  # u can replace this function in bracket as well

"def get_spam_number(x):\n  if x=='spam':\n    return 1\n  return 0"

In [ ]:
df['spam'] = df['Category'].apply(lambda x: 1 if x =='spam' else 0)

In [ ]:
df.shape

(5572, 3)

In [ ]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

**Train test split**

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [ ]:
X_train.shape

(4457,)

In [ ]:
X_test.shape

(1115,)

In [ ]:
type(X_train)

pandas.core.series.Series

In [ ]:
X_train[:4]

4353                    Hows the pain dear?y r u smiling?
4910                             Will do. Have a good day
3078              There is no sense in my foot and penis.
2071    Sexy Singles are waiting for you! Text your AG...
Name: Message, dtype: object

In [ ]:
type(y_train)

pandas.core.series.Series

In [ ]:
y_train[:4]

4353    0
4910    0
3078    0
2071    1
Name: spam, dtype: int64

In [ ]:
type(X_train.values)

numpy.ndarray

**Create bag of words representation using CountVectorizer**

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59338 stored elements and shape (4457, 7763)>

In [ ]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
X_train_cv.shape

(4457, 7763)

In [ ]:
v.get_feature_names_out()[6841]

'the'

In [ ]:
v.get_feature_names_out().shape

(7763,)

In [ ]:
v.vocabulary_

{'hows': 3551,
 'the': 6841,
 'pain': 5079,
 'dear': 2210,
 'smiling': 6288,
 'will': 7534,
 'do': 2398,
 'have': 3387,
 'good': 3213,
 'day': 2197,
 'there': 6859,
 'is': 3773,
 'no': 4823,
 'sense': 6049,
 'in': 3663,
 'my': 4694,
 'foot': 2966,
 'and': 976,
 'penis': 5176,
 'sexy': 6081,
 'singles': 6210,
 'are': 1064,
 'waiting': 7374,
 'for': 2971,
 'you': 7721,
 'text': 6814,
 'your': 7726,
 'age': 872,
 'followed': 2955,
 'by': 1614,
 'gender': 3134,
 'as': 1102,
 'wither': 7562,
 'or': 5006,
 '23f': 366,
 'gay': 3120,
 'men': 4468,
 '23g': 367,
 'want': 7394,
 'new': 4786,
 'video': 7304,
 'phone': 5221,
 '600': 580,
 'anytime': 1016,
 'any': 1006,
 'network': 4777,
 'mins': 4523,
 '400': 482,
 'inclusive': 3672,
 'calls': 1644,
 'downloads': 2458,
 'per': 5179,
 'week': 7454,
 'free': 3018,
 'deltomorrow': 2258,
 'call': 1629,
 '08002888812': 58,
 'reply': 5754,
 'now': 4873,
 'oh': 4942,
 'why': 7518,
 'got': 3231,
 'job': 3856,
 'then': 6854,
 'whats': 7491,
 'up': 7203,
 'o

In [ ]:
X_train_np = X_train_cv.toarray()
X_train_np[:4][0]

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
np.where(X_train_np[0]!=0)

(array([2210, 3551, 5079, 6288, 6841]),)

In [ ]:
X_train[:4][4353]

'Hows the pain dear?y r u smiling?'

In [ ]:
X_train_np[0]

np.int64(1)

In [ ]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [ ]:
X_test_cv = v.transform(X_test)

In [ ]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       985
           1       0.99      0.91      0.95       130

    accuracy                           0.99      1115
   macro avg       0.99      0.95      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [ ]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

In [ ]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])


In [ ]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [ ]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       985
           1       0.99      0.91      0.95       130

    accuracy                           0.99      1115
   macro avg       0.99      0.95      0.97      1115
weighted avg       0.99      0.99      0.99      1115

